services:
  go_web_app_service:
    container_name: goapp-1.24
    image: golang:1.24.1-alpine3.21
    build:
      context: ./backend
      dockerfile: go.dockerfile
    environment:
      DATABASE_URL: 'postgres://postgres:postgres@db:5432/postgres?sslmode=disable'
    ports:
      - 8000:8000
    depends_on:
      - db_service

# database service
  db_service:
    container_name: postgres-14.17
    image: postgres:14.17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432    
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: {}